spring:
  datasource:
      url: jdbc:mysql://localhost:3306/shengdaojia?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
      username: root
      password: app
      driver-class-name: com.mysql.jdbc.Driver
      schema: database/import.sql
      sql-script-encoding: utf-8
      filters: stat
      maxActive: 100
      initialSize: 10
      maxWait: 10000
      minIdle: 5
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 1
      testWhileIdle: true
      testOnBorrow: true
      testOnReturn: false
      poolPreparedStatements: falsey
      maxOpenPreparedStatements: 20
